-- This script seeds demo data for testing (only runs if user is authenticated)
-- In production, this would be generated by actual API usage

-- Insert demo API key (you'll need to be authenticated for this to work)
DO $$
DECLARE
  v_user_id UUID;
BEGIN
  -- Get the current authenticated user
  v_user_id := auth.uid();
  
  IF v_user_id IS NOT NULL THEN
    -- Insert demo API keys
    INSERT INTO api_keys (user_id, key_name, api_key, provider, is_active)
    VALUES 
      (v_user_id, 'OpenAI Production', 'sk-demo-' || gen_random_uuid(), 'openai', true),
      (v_user_id, 'Vercel AI SDK', 'vsk-demo-' || gen_random_uuid(), 'vercel', true);

    -- Insert demo safety alerts
    INSERT INTO safety_alerts (user_id, alert_type, severity, title, description, category, triggered_at)
    VALUES 
      (v_user_id, 'critical', 'high', 'Content Policy Violation Detected', 'Multiple requests flagged for harmful content generation', 'content_policy', NOW() - INTERVAL '2 hours'),
      (v_user_id, 'warning', 'medium', 'High Token Usage', 'Token usage exceeded 80% of monthly limit', 'rate_limit', NOW() - INTERVAL '5 hours'),
      (v_user_id, 'warning', 'medium', 'Unusual Model Behavior', 'Model producing inconsistent safety scores', 'model_behavior', NOW() - INTERVAL '1 day'),
      (v_user_id, 'info', 'low', 'New Safety Filter Active', 'Enhanced content filtering has been enabled', 'safety_filter', NOW() - INTERVAL '3 days');

    -- Insert demo AI interactions
    INSERT INTO ai_interactions (user_id, model, provider, prompt_tokens, completion_tokens, total_tokens, latency_ms, safety_score, flagged, created_at)
    SELECT 
      v_user_id,
      (ARRAY['gpt-4', 'gpt-3.5-turbo', 'claude-3-opus'])[floor(random() * 3 + 1)],
      (ARRAY['openai', 'anthropic'])[floor(random() * 2 + 1)],
      floor(random() * 500 + 50)::INTEGER,
      floor(random() * 1000 + 100)::INTEGER,
      floor(random() * 1500 + 150)::INTEGER,
      floor(random() * 2000 + 100)::INTEGER,
      (random() * 0.3 + 0.7)::DECIMAL(3,2),
      random() < 0.05,
      NOW() - (random() * INTERVAL '7 days')
    FROM generate_series(1, 100);

    -- Insert demo safety stats for the last 7 days
    INSERT INTO safety_stats (user_id, stat_date, total_requests, flagged_requests, avg_safety_score, critical_alerts, warnings, total_tokens, avg_latency_ms)
    SELECT 
      v_user_id,
      CURRENT_DATE - i,
      floor(random() * 500 + 200)::INTEGER,
      floor(random() * 10 + 1)::INTEGER,
      (random() * 0.15 + 0.85)::DECIMAL(3,2),
      floor(random() * 2)::INTEGER,
      floor(random() * 5 + 1)::INTEGER,
      floor(random() * 50000 + 10000)::INTEGER,
      floor(random() * 500 + 300)::INTEGER
    FROM generate_series(0, 6) i;

  END IF;
END $$;
